### ISSUE TITLE
运行一段时间后闪退了

### ISSUE THREAD

**Issue by 1040536527** [superconvert/smart_rtmpd#12]
我开了一个直播间，局域网用户30多人访问，但是过了一会闪退了，直播了2个小时，闪退了三四次，闪退时程序在后台也退出了，需要重新开启软件

**Comment by superconvert** [comment]
是window版本吧，应该是内存不够了，调整配置文件里面内存配置 值改小。或者用Linux版本，或者购买我们带web管理的程序

**Comment by superconvert** [comment]
已解决

>
