### ISSUE TITLE
ipv6下似乎无法通过网页看直播

### ISSUE THREAD

**Issue by CHATGPB** [superconvert/smart_rtmpd#13]
下图是ipv6
![image](https://github.com/user-attachments/assets/ee94966c-d552-4176-b001-ba36caddfe4b)
ipv4可以正常展开
![image](https://github.com/user-attachments/assets/cfc572d2-2f04-438d-b0eb-00fc32a86da7)

**Comment by superconvert** [comment]
After discussion with the questioner, it was found that the problem was caused by the wrong configuration
