### ISSUE TITLE
免费么

### ISSUE THREAD

**Issue by fortunerains** [superconvert/smart_rtmpd#3]

**Comment by superconvert** [comment]
是的
----- 原始邮件 -----
发件人：chunyexixiaoyu <notifications@github.com>
收件人：superconvert/smart_rtmpd <smart_rtmpd@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：[superconvert/smart_rtmpd]_免费么_(#3)
日期：2021年01月22日 11点02分

**Comment by superconvert** [comment]
It's freeware
