### ISSUE TITLE
使用/rec推流后，用hls模式，存储的视频命名为年月日，每次保存的视频都会覆盖上一次的视频，dash没有问题

### ISSUE THREAD

**Issue by zkassing** [superconvert/smart_rtmpd#5]

**Comment by superconvert** [comment]
我们核对一下 理论上文件是以时分秒存储的，你们视频gop是多少

**Comment by zkassing** [comment]
> 我们核对一下 理论上文件是以时分秒存储的，你们视频gop是多少

您好，我使用的是OBS推流我的电脑窗口，全部默认设置下出现的情况

服务器配置rec市场为1分钟，dash可以已是分秒存储，但是hls不可以。切换5分钟一样的问题。

**Comment by zkassing** [comment]
使用的是windows版本

**Comment by superconvert** [comment]
此问题已经解决，请等待下一个版本。this issue had been fixed, pls wait next version!

**Comment by superconvert** [comment]
Pls download new version!
