### ISSUE TITLE
希望支持ipv6

### ISSUE THREAD

**Issue by LittleArray** [superconvert/smart_rtmpd#7]
希望支持ipv6，家里的nas有ipv6没ipv4

**Comment by superconvert** [comment]
已经支持，配置文件内有对应的配置项，ipv6的开关打开就行

**Comment by LittleArray** [comment]
感谢支持

**Comment by LittleArray** [comment]
![image](https://user-images.githubusercontent.com/88972417/233782949-3128d0c5-7eb8-415d-9328-ce6a66fd7cf4.png)
应该修改那个配置啊，找不到开关或者配置

**Comment by superconvert** [comment]
config.xml里面的ipv6
